export default function useControllerProps({
  setMode,
  setOnboardingPage,
  setShowSignInModal,
  setSignInEmail,
  setShowResetModal,
  setShowShareModal,
  setCollaboratorEmail,
  setIsViewOnly,
  setShowMyTripsModal,
  setShowPastSavedTrips,
  setCloudVisibility,
  setImportJson,
  setShowImportModal,
  setView,
  setFilter,
  setSelectedId,
  handleSignIn,
  handleSignOut,
  handleOpenCloudTrip,
  handleDeleteCloudTrip,
  handleStartFromTemplate,
  handleStartFromScratch,
  handleStartFromQuickTemplate,
  openImportModal,
  handleSaveAndPreview,
  handleCancelEdit,
  handleGoHome,
  handleReset,
  confirmReset,
  handleFixIssue,
  handleShare,
  handleSaveSharedCopy,
  handleEditTrip,
  submitGoogleSignIn,
  submitSignIn,
  handleShareAccessChange,
  handleAddCollaborator,
  handleRemoveCollaborator,
  copyShareLink,
  handleImportJson,
  isSupabaseConfigured,
  user,
  signInEmail,
  signInLoading,
  onboardingPage,
  savedUpcomingTrips,
  savedPastTrips,
  showPastSavedTrips,
  extractCoverImage,
  formatVisibilityLabel,
  quickTemplates,
  isAdminUser,
  showImportModal,
  importJson,
  importError,
  toasts,
  showSignInModal,
  showResetModal,
  showShareModal,
  publishIssues,
  currentShareURL,
  canCopyShareLink,
  cloudSaving,
  cloudTripId,
  isCloudOwnedByCurrentUser,
  cloudShareAccess,
  collaboratorEmail,
  collaboratorsLoading,
  collaborators,
  isViewOnly,
  showMyTripsModal,
  myTripsLoading,
  myTrips,
  cloudVisibility,
  tripData,
  builderStartTab,
  activePalette,
  tripConfig,
  isSharedCloudTrip,
  canCollaborateOnSharedTrip,
  copiedFrom,
  canSaveSharedCopy,
  canEditCurrentTrip,
  cloudSlug,
  flights,
  days,
  filtered,
  showMaps,
  imgClass,
  selectedId,
  dayBadges,
  selectedDay,
  view,
  filter,
}) {
  const overlayProps = {
    toasts,
    showSignInModal,
    onCloseSignInModal: () => setShowSignInModal(false),
    isSupabaseConfigured,
    signInEmail,
    onSignInEmailChange: setSignInEmail,
    onGoogleSignIn: submitGoogleSignIn,
    onSubmitSignIn: submitSignIn,
    signInLoading,
    showResetModal,
    onCloseResetModal: () => setShowResetModal(false),
    onConfirmReset: confirmReset,
    showShareModal,
    onCloseShareModal: () => setShowShareModal(false),
    publishIssues,
    onFixIssue: handleFixIssue,
    currentShareURL,
    canCopyShareLink,
    onCopyShareLink: copyShareLink,
    user,
    cloudSaving,
    onOpenSignInFromShare: () => {
      setShowShareModal(false);
      handleSignIn();
    },
    cloudTripId,
    isCloudOwnedByCurrentUser,
    cloudShareAccess,
    onShareAccessChange: handleShareAccessChange,
    collaboratorEmail,
    onCollaboratorEmailChange: setCollaboratorEmail,
    onAddCollaborator: handleAddCollaborator,
    collaboratorsLoading,
    collaborators,
    onRemoveCollaborator: handleRemoveCollaborator,
    isViewOnly,
    onViewOnlyChange: setIsViewOnly,
    showMyTripsModal,
    onCloseMyTripsModal: () => setShowMyTripsModal(false),
    myTripsLoading,
    myTrips,
    savedUpcomingTrips,
    savedPastTrips,
    showPastSavedTrips,
    onTogglePast: () => setShowPastSavedTrips((prev) => !prev),
    onOpenTrip: handleOpenCloudTrip,
    onDeleteTrip: handleDeleteCloudTrip,
    extractCoverImage,
    formatVisibilityLabel,
    cloudVisibility,
    onChangeVisibility: setCloudVisibility,
    showImportModal,
    isAdminUser,
    importJson,
    onImportJsonChange: setImportJson,
    importError,
    onCloseImportModal: () => setShowImportModal(false),
    onImportJson: handleImportJson,
  };

  const authProps = {
    user,
    isSupabaseConfigured,
    signInEmail,
    onEmailChange: setSignInEmail,
    onGoogleSignIn: submitGoogleSignIn,
    onSubmitSignIn: submitSignIn,
    signInLoading,
    onContinueToApp: () => {
      window.history.replaceState(null, "", "/");
      setMode("onboarding");
    },
  };

  const onboardingProps = {
    onboardingPage,
    onSwitchPage: (page) => {
      setOnboardingPage(page);
      window.history.pushState(null, "", page === "trips" ? "/app" : "/new");
    },
    user,
    onGoCreate: () => {
      setOnboardingPage("create");
      window.history.pushState(null, "", "/new");
    },
    onSignOut: handleSignOut,
    onSignIn: handleSignIn,
    savedUpcomingTrips,
    savedPastTrips,
    showPastSavedTrips,
    onTogglePast: () => setShowPastSavedTrips((prev) => !prev),
    onOpenTrip: handleOpenCloudTrip,
    extractCoverImage,
    formatVisibilityLabel,
    onStartFromTemplate: handleStartFromTemplate,
    onStartFromScratch: handleStartFromScratch,
    quickTemplates,
    onStartFromQuickTemplate: handleStartFromQuickTemplate,
    isAdminUser,
    onOpenImportModal: openImportModal,
  };

  const builderProps = {
    tripData,
    onSave: handleSaveAndPreview,
    onCancel: handleCancelEdit,
    onHome: handleGoHome,
    onReset: handleReset,
    initialTab: builderStartTab,
    isAdmin: isAdminUser,
  };

  const viewProps = {
    activePaletteBg: activePalette.bg,
    tripTitle: tripConfig.title,
    isSharedCloudTrip,
    canCollaborateOnSharedTrip,
    copiedFromOwnerId: copiedFrom?.ownerId,
    onGoHome: handleGoHome,
    view,
    onChangeView: setView,
    filter,
    onChangeFilter: setFilter,
    onShare: () => handleShare(setShowShareModal),
    canSaveSharedCopy,
    onSaveSharedCopy: handleSaveSharedCopy,
    cloudSaving,
    canEditCurrentTrip,
    onEditTrip: handleEditTrip,
    onReset: handleReset,
    user,
    onSignIn: handleSignIn,
    onSignOut: handleSignOut,
    tripConfig,
    cloudSlug,
    cloudTripId,
    isSupabaseConfigured,
    flights,
    days,
    filtered,
    showMaps,
    imgClass,
    selectedId,
    onSelectDay: setSelectedId,
    dayBadges,
    selectedDay,
    activePaletteCard: activePalette.card,
  };

  return {
    overlayProps,
    authProps,
    onboardingProps,
    builderProps,
    viewProps,
  };
}
