export default function useOverlayProps({
  toasts,
  showSignInModal,
  setShowSignInModal,
  isSupabaseConfigured,
  signInEmail,
  setSignInEmail,
  submitGoogleSignIn,
  submitSignIn,
  signInLoading,
  showResetModal,
  setShowResetModal,
  confirmReset,
  showShareModal,
  setShowShareModal,
  publishIssues,
  handleFixIssue,
  currentShareURL,
  canCopyShareLink,
  copyShareLink,
  user,
  cloudSaving,
  handleSignIn,
  cloudTripId,
  isCloudOwnedByCurrentUser,
  cloudShareAccess,
  handleShareAccessChange,
  collaboratorEmail,
  setCollaboratorEmail,
  handleAddCollaborator,
  collaboratorsLoading,
  collaborators,
  handleRemoveCollaborator,
  isViewOnly,
  setIsViewOnly,
  showMyTripsModal,
  setShowMyTripsModal,
  myTripsLoading,
  myTrips,
  savedUpcomingTrips,
  savedPastTrips,
  showPastSavedTrips,
  setShowPastSavedTrips,
  handleOpenCloudTrip,
  handleDeleteCloudTrip,
  extractCoverImage,
  formatVisibilityLabel,
  cloudVisibility,
  setCloudVisibility,
  showImportModal,
  isAdminUser,
  importJson,
  setImportJson,
  importError,
  setShowImportModal,
  handleImportJson,
}) {
  return {
    toasts,
    showSignInModal,
    onCloseSignInModal: () => setShowSignInModal(false),
    isSupabaseConfigured,
    signInEmail,
    onSignInEmailChange: setSignInEmail,
    onGoogleSignIn: submitGoogleSignIn,
    onSubmitSignIn: submitSignIn,
    signInLoading,
    showResetModal,
    onCloseResetModal: () => setShowResetModal(false),
    onConfirmReset: confirmReset,
    showShareModal,
    onCloseShareModal: () => setShowShareModal(false),
    publishIssues,
    onFixIssue: handleFixIssue,
    currentShareURL,
    canCopyShareLink,
    onCopyShareLink: copyShareLink,
    user,
    cloudSaving,
    onOpenSignInFromShare: () => {
      setShowShareModal(false);
      handleSignIn();
    },
    cloudTripId,
    isCloudOwnedByCurrentUser,
    cloudShareAccess,
    onShareAccessChange: handleShareAccessChange,
    collaboratorEmail,
    onCollaboratorEmailChange: setCollaboratorEmail,
    onAddCollaborator: handleAddCollaborator,
    collaboratorsLoading,
    collaborators,
    onRemoveCollaborator: handleRemoveCollaborator,
    isViewOnly,
    onViewOnlyChange: setIsViewOnly,
    showMyTripsModal,
    onCloseMyTripsModal: () => setShowMyTripsModal(false),
    myTripsLoading,
    myTrips,
    savedUpcomingTrips,
    savedPastTrips,
    showPastSavedTrips,
    onTogglePast: () => setShowPastSavedTrips((prev) => !prev),
    onOpenTrip: handleOpenCloudTrip,
    onDeleteTrip: handleDeleteCloudTrip,
    extractCoverImage,
    formatVisibilityLabel,
    cloudVisibility,
    onChangeVisibility: setCloudVisibility,
    showImportModal,
    isAdminUser,
    importJson,
    onImportJsonChange: setImportJson,
    importError,
    onCloseImportModal: () => setShowImportModal(false),
    onImportJson: handleImportJson,
  };
}
