export default function useScreenProps({
  setMode,
  setOnboardingPage,
  user,
  isSupabaseConfigured,
  signInEmail,
  setSignInEmail,
  submitGoogleSignIn,
  submitSignIn,
  signInLoading,
  onboardingPage,
  handleSignOut,
  handleSignIn,
  savedUpcomingTrips,
  savedPastTrips,
  showPastSavedTrips,
  setShowPastSavedTrips,
  handleOpenCloudTrip,
  extractCoverImage,
  formatVisibilityLabel,
  handleStartFromTemplate,
  handleStartFromScratch,
  quickTemplates,
  handleStartFromQuickTemplate,
  isAdminUser,
  openImportModal,
  tripData,
  handleSaveAndPreview,
  handleCancelEdit,
  handleGoHome,
  handleReset,
  builderStartTab,
  activePalette,
  tripConfig,
  isSharedCloudTrip,
  canCollaborateOnSharedTrip,
  copiedFrom,
  view,
  setView,
  filter,
  setFilter,
  handleShare,
  setShowShareModal,
  canSaveSharedCopy,
  handleSaveSharedCopy,
  cloudSaving,
  canEditCurrentTrip,
  handleEditTrip,
  cloudSlug,
  cloudTripId,
  flights,
  days,
  filtered,
  showMaps,
  imgClass,
  selectedId,
  setSelectedId,
  dayBadges,
  selectedDay,
}) {
  const authProps = {
    user,
    isSupabaseConfigured,
    signInEmail,
    onEmailChange: setSignInEmail,
    onGoogleSignIn: submitGoogleSignIn,
    onSubmitSignIn: submitSignIn,
    signInLoading,
    onContinueToApp: () => {
      window.history.replaceState(null, "", "/");
      setMode("onboarding");
    },
  };

  const onboardingProps = {
    onboardingPage,
    onSwitchPage: (page) => {
      setOnboardingPage(page);
      window.history.pushState(null, "", page === "trips" ? "/app" : "/new");
    },
    user,
    onGoCreate: () => {
      setOnboardingPage("create");
      window.history.pushState(null, "", "/new");
    },
    onSignOut: handleSignOut,
    onSignIn: handleSignIn,
    savedUpcomingTrips,
    savedPastTrips,
    showPastSavedTrips,
    onTogglePast: () => setShowPastSavedTrips((prev) => !prev),
    onOpenTrip: handleOpenCloudTrip,
    extractCoverImage,
    formatVisibilityLabel,
    onStartFromTemplate: handleStartFromTemplate,
    onStartFromScratch: handleStartFromScratch,
    quickTemplates,
    onStartFromQuickTemplate: handleStartFromQuickTemplate,
    isAdminUser,
    onOpenImportModal: openImportModal,
  };

  const builderProps = {
    tripData,
    onSave: handleSaveAndPreview,
    onCancel: handleCancelEdit,
    onHome: handleGoHome,
    onReset: handleReset,
    initialTab: builderStartTab,
    isAdmin: isAdminUser,
  };

  const viewProps = {
    activePaletteBg: activePalette.bg,
    tripTitle: tripConfig.title,
    isSharedCloudTrip,
    canCollaborateOnSharedTrip,
    copiedFromOwnerId: copiedFrom?.ownerId,
    onGoHome: handleGoHome,
    view,
    onChangeView: setView,
    filter,
    onChangeFilter: setFilter,
    onShare: () => handleShare(setShowShareModal),
    canSaveSharedCopy,
    onSaveSharedCopy: handleSaveSharedCopy,
    cloudSaving,
    canEditCurrentTrip,
    onEditTrip: handleEditTrip,
    onReset: handleReset,
    user,
    onSignIn: handleSignIn,
    onSignOut: handleSignOut,
    tripConfig,
    cloudSlug,
    cloudTripId,
    isSupabaseConfigured,
    flights,
    days,
    filtered,
    showMaps,
    imgClass,
    selectedId,
    onSelectDay: setSelectedId,
    dayBadges,
    selectedDay,
    activePaletteCard: activePalette.card,
  };

  return {
    authProps,
    onboardingProps,
    builderProps,
    viewProps,
  };
}
