import useShareActions from "../useShareActions";

export default function useTripShareDomain({
  user,
  tripData,
  cloudTripId,
  cloudSlug,
  shareToken,
  cloudVisibility,
  cloudShareAccess,
  cloudOwnerId,
  collaboratorEmail,
  isCloudOwnedByCurrentUser,
  setCloudSaving,
  setCloudTripId,
  setCloudSlug,
  setShareToken,
  setCloudVisibility,
  setCloudShareAccess,
  setCloudOwnerId,
  setCloudCollaboratorRole,
  setCollaboratorEmail,
  setCollaboratorsLoading,
  refreshMyTrips,
  refreshCollaborators,
  pushToast,
}) {
  return useShareActions({
    user,
    tripData,
    cloudTripId,
    cloudSlug,
    shareToken,
    cloudVisibility,
    cloudShareAccess,
    cloudOwnerId,
    collaboratorEmail,
    isCloudOwnedByCurrentUser,
    setCloudSaving,
    setCloudTripId,
    setCloudSlug,
    setShareToken,
    setCloudVisibility,
    setCloudShareAccess,
    setCloudOwnerId,
    setCloudCollaboratorRole,
    setCollaboratorEmail,
    setCollaboratorsLoading,
    refreshMyTrips,
    refreshCollaborators,
    pushToast,
  });
}
